FROM ghcr.io/gleam-lang/gleam:v1.14.0-erlang-alpine

WORKDIR /app

COPY apps/orchestrator apps/orchestrator
RUN cd apps/orchestrator && gleam build

WORKDIR /app/apps/orchestrator
CMD ["gleam", "run", "-m", "e2e_test"]
